input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.Happy)
    basic.clearScreen()
    basic.pause(100)
    basic.showIcon(IconNames.Happy)
    basic.clearScreen()
    basic.pause(100)
    basic.showIcon(IconNames.Happy)
    basic.clearScreen()
    basic.pause(100)
    basic.showIcon(IconNames.Happy)
    basic.clearScreen()
    basic.pause(100)
})
input.onButtonPressed(Button.B, function () {
    basic.showIcon(IconNames.Sad)
    basic.clearScreen()
    basic.pause(100)
    basic.showIcon(IconNames.Sad)
    basic.clearScreen()
    basic.pause(100)
    basic.showIcon(IconNames.Sad)
    basic.clearScreen()
    basic.pause(100)
    basic.showIcon(IconNames.Sad)
    basic.clearScreen()
    basic.pause(100)
})
basic.forever(function () {
	
})
